  export interface Escola {
    id: number
    NOMEDEP: string
    DE: string
    MUN: string
    DISTR: string
    CODESC: string
    NOMESC: string
    TIPOESC: number
    TIPOESC_DESC: string
    CODSIT: string
    SALAS_AULA: number
    SALAS_ED_INF: number
    SALAS_ED_ESP: number
    SALAS_ED_ART: number
    SALA_RECURSO: number
    TOT_SALAS_AULA: number
    AUDITORIO: number
    ANFITEATRO: number
    TEATRO: number
    CANTINA: number
    COPA: number
    COZINHA: number
    REFEITORIO: number
    DEPOSITO_ALIMENTOS: number
    DESPENSA: number
    TOT_DESPENSA: number
    SALA_LEITURA: number
    BIBLIOTECA: number
    TOT_SALA_LEITURA: number
    QUADRA_COBERTA: number
    QUADRA_DESCOBERTA: number
    GINASIO: number
    TOT_QUADRA: number
    QUADRA_AREIA: number
    QUADRA_GRAMA: number
    CAMPO_FUTEBOL: number
    GABINETE_DENTARIO: number
    CONSULTORIO_MEDICO: number
    ENFERMARIA: number
    AMBULATORIO: number
    ALMOXARIFADO: number
    ARQUIVO: number
    REPROGRAFIA: number
    SALA_GREMIO: number
    DIRETORIA: number
    VICEDIRETORIA: number
    SALA_PROF: number
    SECRETARIA: number
    SALA_ORIENT_ED: number
    SALA_COORD_PEDAG: number
    PATIO_COBERTO: number
    PATIO_DESCOBERTO: number
    ZELADORIA: number
    VESTIARIO_FEM: number
    VESTIARIO_MASC: number
    TOT_VESTIARIO: number
    VIDEOTECA: number
    SALA_TV: number
    LAB_INFO: number
    LAB_CIENCIAS: number
    LAB_FISICA: number
    LAB_QUIMICA: number
    LAB_BIOLOGIA: number
    LAB_CIENCIA_FISICA_BIOLOGICA: number
    TOT_LAB_CIENCIA: number
    LAB_LINGUAS: number
    LAB_MULTIUSO: number
    OFICINA: number
    PLAYGROUND: number
    DORMITORIO: number
    BERCARIO: number
    SANITARIO_ADEQ_PRE: number
    SANITARIO_ADEQ_PRE_FEM: number
    SANITARIO_ADEQ_PRE_MASC: number
    SANITARIO_ADEQ_DEF: number
    SANITARIO_ADEQ_DEF_FEM: number
    SANITARIO_ADEQ_DEF_MASC: number
    SANITARIO_AL_MASC: number
    SANITARIO_AL_FEM: number
    TOT_SANITARIO_AL: number
    SANITARIO_FUNC_FEM: number
    SANITARIO_FUNC_MASC: number
    TOT_SANITARIO_FUNC: number
    DEPEND_ADEQ_DEF: number
    SALA_ED_FISICA: number
    PISCINA: number
    PORTARIA: number
    SALA_PROG_ESC_FAMILIA: number
    BRINQUEDOTECA: number
    FRALDARIO: number
    LACTARIO: number
    LAVANDERIA: number
    SOLARIO: number
    SALA_ESPERA: number
    SALA_INSPETOR: number
    SALA_REUNIAO: number
    TESOURARIA: number
    SALA_REFORCO: number
    SALA_DIRETOR_TECNICO: number
    GARAGEM_ONIBUS: number
    SALA_FISIOTERAPIA: number
    SALA_PSICOLOGIA: number
    SALA_FONOAUDIOLOGIA: number
    SALA_EVENTOS: number
    SALA_ASSIST_SOCIAL: number
    SALA_TERAPIA_EDUC: number
    ABATEDOURO: number
    ALOJAMENTO_FEM: number
    ALOJAMENTO_MASC: number
    TOT_ALOJAMENTO: number
    AREA_SERVICO: number
    BAZAR: number
    CASA_MAQUINA: number
    CASA_FUNC: number
    CHURRASQUEIRA: number
    DEPOSITOS_CEREAIS: number
    ELEVADOR: number
    ESTACIONAMENTO: number
    ESTUFA: number
    GALPAO_AVES_CORTE: number
    GALPAO_AVES_POSTURA: number
    GALPAO_BOVINOS_LEITE: number
    GALPAO_CUNICULTURA: number
    GALPAO_MAQ_AGRICOLA: number
    GALPAO_OVINOS_CAPRINOS: number
    GALPAO_SUINO: number
    GRAFICA: number
    HORTA: number
    LAB_DIDATICA: number
    LAB_JUNIOR: number
    LAB_ENFERMAGEM: number
    LAB_ESTETICA: number
    LAB_PSICOPEDAGOGIA: number
    LAB_TURISMO: number
    LAVATORIO: number
    MANGUEIRA: number
    MINHOCARIO: number
    PACKING_HOUSE: number
    POMAR: number
    PSICULTURA: number
    RECEPCAO: number
    SALA_ATENDIMENTO: number
    SALA_ATEND_PSICOLOGICO: number
    SALA_AUX_COORDENACAO: number
    SALA_DADOS: number
    SALA_DEP_PESSOAL: number
    SALA_ED_RELIGIOSA: number
    SALA_ENERGIA_ELETRICA: number
    SALA_ENTRETENIMENTO: number
    SALA_ESTAGIO: number
    SALA_GINASTICA: number
    SALA_INSUMO_AGRICOLA: number
    SALA_INSUMO_VETERINARIO: number
    SALA_MARKETING: number
    SALA_MATRICULA: number
    SALA_MUSICA: number
    SALA_POS_GRADUACAO: number
    SALA_ORDENHA: number
    SALA_PROC_PROD_AGROPECUARIOS: number
    SALA_SEGURANCA: number
    SALA_TELEFONIA: number
    SALA_FINANCEIRO: number
    SALA_PASTORAL: number
    SALA_RESERV_AGUA: number
    SERVIDOR: number
    SILO: number
    VARANDA: number
    VIVEIRO: number
    SALA_REORG_NEURO: number
    SALA_TERAPIA_OCUP: number
    SALA_SERIGRAFIA: number
    SALA_MARCENARIA: number
    QUIOSQUE: number
  }
